version: '2.3'

x-volumes:
  &default-volumes
  volumes:
    - ./files:/app/sites/default/files:delegated

x-environment:
  &default-environment
  CLI_IMAGE: ${CLI_IMAGE:-govcms8}
  DRUPAL_VERSION: ${DRUPAL_VERSION:-8}
  LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcmslagoon.docker.amazee.io}
  X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
  SOLR_VERSION: ${SOLR_VERSION:-7.5.x}
  CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}

services:

  cli:
    build:
      context: .
      dockerfile: $PWD/images/govcms/${DRUPAL_VERSION:-8}.x/Dockerfile
      args:
        DRUPAL_CORE_VERSION: ${DRUPAL_CORE_VERSION}
        GOVCMS_PROJECT_VERSION: ${GOVCMS_PROJECT_VERSION}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.3}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms${DRUPAL_VERSION:-8}
    << : *default-volumes
    environment:
      << : *default-environment

  test:
    build:
      context: .
      dockerfile: $PWD/images/test/${DRUPAL_VERSION:-8}.x/Dockerfile
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/${CLI_IMAGE:-govcms8}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.3}
        SITE_AUDIT_VERSION: ${SITE_AUDIT_VERSION:-7.x-3.x}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms${DRUPAL_VERSION:-8}test
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  nginx:
    build:
      context: .
      dockerfile: $PWD/images/drupal/nginx/Dockerfile
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/${CLI_IMAGE:-govcms8}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/nginx-drupal
    << : *default-volumes
    environment:
      << : *default-environment
      LAGOON_LOCALDEV_URL: ${LOCALDEV_URL_NGINX:-http://govcmslagoon.docker.amazee.io}
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: $PWD/images/php/Dockerfile
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/${CLI_IMAGE:-govcms8}
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION:-7.3}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/php
    << : *default-volumes
    environment:
      << : *default-environment

  mariadb:
    build:
      context: .
      dockerfile: $PWD/images/drupal/mariadb/Dockerfile
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/mariadb-drupal
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment

  redis:
    build:
      context: .
      dockerfile: $PWD/images/redis/Dockerfile
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/redis
    environment:
      << : *default-environment

  solr:
    build:
      context: .
      dockerfile: $PWD/images/solr/${SOLR_VERSION:-7.5.x}/Dockerfile
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/${CLI_IMAGE:-govcms8}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/solr
    ports:
      - "8983" # Find port on host with `docker-compose port solr 8983`
    environment:
      << : *default-environment

  varnish:
    build:
      context: .
      dockerfile: $PWD/images/drupal/varnish/Dockerfile
      args:
        LAGOON_IMAGE_VERSION: ${LAGOON_IMAGE_VERSION:-latest}
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/varnish-drupal
    environment:
      << : *default-environment
      VARNISH_BYPASS: "true"
    networks:
      - amazeeio-network
      - default

  chrome:
    build:
      context: .
      dockerfile: $PWD/images/chrome/Dockerfile
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/chrome
    shm_size: '1gb'
    depends_on:
      - test
    << : *default-volumes

networks:
  amazeeio-network:
    external: true
