name: govcms

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  govcms7:
    name: GovCMS 7
    runs-on: ubuntu-latest
    env:
      DRUPAL_VERSION: 7
      SOLR_VERSION: 6.6.x
      GOVCMS_PROJECT_VERSION: 7.x-3.x
      DOCKERHUB_NAMESPACE: govcms7lagoon
      CLI_IMAGE: govcms7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build GovCMS
        run: docker-compose -p govcms7 build --no-cache
      - name: Start GovCMS
        run: docker-compose -p govcms7 up -d
      - name: Stop GovCMS
        run: docker-compose -p govcms7 down
      - name: Remove GovCMS
        run: docker-compose -p govcms7 rm
  govcms8:
    name: GovCMS 8
    runs-on: ubuntu-latest
    env:
      DRUPAL_VERSION: 8
      SOLR_VERSION: 7.5.x
      GOVCMS_PROJECT_VERSION: 1.4.0
      DRUPAL_CORE_VERSION: 8.8.6
      DOCKERHUB_NAMESPACE: govcms8lagoon
      CLI_IMAGE: govcms8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build GovCMS
        run: docker-compose -p govcms8 build --no-cache
      - name: Start GovCMS
        run: docker-compose -p govcms8 up -d
      - name: Stop GovCMS
        run: docker-compose -p govcms8 down
      - name: Remove GovCMS
        run: docker-compose -p govcms8 rm
  govcms9:
    name: GovCMS 9
    runs-on: ubuntu-latest
    env:
      DRUPAL_VERSION: 9
      SOLR_VERSION: 7.5.x
      DRUPAL_CORE_VERSION: 9.0.2
      DOCKERHUB_NAMESPACE: govcms9lagoon
      CLI_IMAGE: govcms9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build GovCMS
        run: docker-compose -p govcms9 build --no-cache
      - name: Start GovCMS
        run: docker-compose -p govcms9 up -d
      - name: Stop GovCMS
        run: docker-compose -p govcms9 down
      - name: Remove GovCMS
        run: docker-compose -p govcms9 rm
